"""Typed appearance and physical material catalogue."""

from golem.materials.core import (
    DEFAULT_APPEARANCE_MATERIAL_ID,
    MATERIAL_CATALOGUE,
    AcceptedMaterial,
    AppearanceMaterial,
    AppearanceMaterialId,
    CompressibleGas,
    CompressibleGasMaterialId,
    EvidenceKind,
    FluidPhaseLimits,
    GasEquationOfState,
    IncompressibleFluid,
    IncompressibleFluidMaterialId,
    IsotropicSolid,
    IsotropicSolidMaterialId,
    MaterialCatalogue,
    MaterialEvidence,
    MaterialKind,
    PressureInterval,
    RejectedMaterial,
    TemperatureInterval,
    UnknownMaterialObstruction,
)
from golem.materials.decode import (
    decode_appearance_material,
    decode_compressible_gas,
    decode_incompressible_fluid,
    decode_isotropic_solid,
    resolve_appearance_material,
)
from golem.materials.projection import appearance_material_to_dict

__all__ = [
    "DEFAULT_APPEARANCE_MATERIAL_ID",
    "MATERIAL_CATALOGUE",
    "AcceptedMaterial",
    "AppearanceMaterial",
    "AppearanceMaterialId",
    "CompressibleGas",
    "CompressibleGasMaterialId",
    "EvidenceKind",
    "FluidPhaseLimits",
    "GasEquationOfState",
    "IncompressibleFluid",
    "IncompressibleFluidMaterialId",
    "IsotropicSolid",
    "IsotropicSolidMaterialId",
    "MaterialCatalogue",
    "MaterialEvidence",
    "MaterialKind",
    "PressureInterval",
    "RejectedMaterial",
    "TemperatureInterval",
    "UnknownMaterialObstruction",
    "appearance_material_to_dict",
    "decode_appearance_material",
    "decode_compressible_gas",
    "decode_incompressible_fluid",
    "decode_isotropic_solid",
    "resolve_appearance_material",
]
