"""Typed assembly operating intent for M7 coupled-substrate descent.

The assembly document supplies semantic service intent, never solver topology or
field values.  Decoding is total and applicative: malformed or incompatible
local declarations descend to addressed obstructions; only a fully compatible
section glues into ``ServiceIntent``.
"""

from __future__ import annotations

from golem.assembly.service.address import (
    AcceptedSemanticAddress,
    BoneAddress,
    ContactAddress,
    ElementAddress,
    MalformedSemanticAddressObstruction,
    MountAddress,
    PortAddress,
    RegionAddress,
    RejectedSemanticAddress,
    SemanticAddress,
    SemanticAddressKind,
    SemanticAddressResult,
    decode_semantic_address,
    semantic_address_kind,
    semantic_address_token,
)
from golem.assembly.service.model import (
    AmbientCondition,
    AmbientHeatTransferPolicy,
    AppliedLoad,
    ChannelResolutionPolicy,
    CoolantService,
    DecodedServiceIntent,
    EvidenceObligation,
    ForceLoad,
    HeatSource,
    JointInterface,
    JointLaw,
    ManufacturingLimits,
    MomentLoad,
    OperatingLimits,
    PhysicalEvidenceStatus,
    PhysicsEvidencePolicy,
    PowerPumpBudget,
    PressurePumpBudget,
    PumpBudget,
    SIScale,
    ServiceCase,
    ServiceIntent,
    SolidConstitutiveModel,
    SolidMaterialAssignment,
    SolidMaterialRole,
    Support,
    SupportLaw,
    Vector3,
    VisualOnlyServiceIntent,
)
from golem.assembly.service.outcome import (
    AcceptedServiceIntent,
    ContradictorySupportObstruction,
    DuplicateMaterialAssignmentObstruction,
    DuplicateServiceCaseObstruction,
    InvalidSemanticAddressKindObstruction,
    MalformedServiceIntentObstruction,
    MaterialValidityObstruction,
    MissingHeatSinkObstruction,
    MissingUnitScaleObstruction,
    NonPositiveBudgetObstruction,
    RejectedServiceIntent,
    ServiceIntentObstruction,
    ServiceIntentResult,
    UnknownPhysicalMaterialObstruction,
    UnknownSemanticAddressObstruction,
    UnsupportedConstitutiveModelObstruction,
)
from golem.assembly.service.intent import decode_service_intent


__all__ = [
    "SemanticAddressKind",
    "ElementAddress",
    "RegionAddress",
    "BoneAddress",
    "PortAddress",
    "ContactAddress",
    "MountAddress",
    "SemanticAddress",
    "semantic_address_token",
    "semantic_address_kind",
    "decode_semantic_address",
    "AcceptedSemanticAddress",
    "RejectedSemanticAddress",
    "SemanticAddressResult",
    "PhysicalEvidenceStatus",
    "SolidConstitutiveModel",
    "SolidMaterialRole",
    "SupportLaw",
    "JointLaw",
    "AmbientHeatTransferPolicy",
    "ChannelResolutionPolicy",
    "EvidenceObligation",
    "Vector3",
    "SIScale",
    "SolidMaterialAssignment",
    "ForceLoad",
    "MomentLoad",
    "AppliedLoad",
    "Support",
    "JointInterface",
    "HeatSource",
    "AmbientCondition",
    "PressurePumpBudget",
    "PowerPumpBudget",
    "PumpBudget",
    "CoolantService",
    "ManufacturingLimits",
    "OperatingLimits",
    "PhysicsEvidencePolicy",
    "ServiceCase",
    "VisualOnlyServiceIntent",
    "ServiceIntent",
    "DecodedServiceIntent",
    "MalformedServiceIntentObstruction",
    "MalformedSemanticAddressObstruction",
    "MissingUnitScaleObstruction",
    "UnknownSemanticAddressObstruction",
    "InvalidSemanticAddressKindObstruction",
    "ContradictorySupportObstruction",
    "MissingHeatSinkObstruction",
    "UnsupportedConstitutiveModelObstruction",
    "NonPositiveBudgetObstruction",
    "UnknownPhysicalMaterialObstruction",
    "MaterialValidityObstruction",
    "DuplicateServiceCaseObstruction",
    "DuplicateMaterialAssignmentObstruction",
    "ServiceIntentObstruction",
    "AcceptedServiceIntent",
    "RejectedServiceIntent",
    "ServiceIntentResult",
    "decode_service_intent",
]
