"""GOLEM immutable linear-balance algebra for hydraulics and heat.

``solve_balance`` glues local symmetric conductance, directed transport, source,
fixed-boundary, and ambient-exchange terms into one sparse global section.  It
returns the authoritative field together with every interface flux, addressed
cell residual, fixed-boundary supply, and global imbalance.  Invalid local terms,
unglued components, unsupported heat-transfer regimes, and sparse-solver
failures remain typed obstructions.  Hydraulics and thermal analysis are local
interpreters of this one algebra; neither owns a parallel matrix system.

Modules: ``vocabulary`` (closed enums + solver DOF identity), ``arrays`` (numeric
floor), ``result`` (obstructions + ``Result`` + renderer), ``problem`` (input
carriers), ``section`` (output carriers), ``validate`` (structural guards),
``solve`` (the solver core), ``interpreter`` (the extension seam), ``correlation``
(heat-transfer laws), ``nusselt`` (correlation algebra), ``thermal`` (the reference
interpreter).
"""

from __future__ import annotations

from golem.kernel.sheaf.correlation import (
    ChurchillChuIsothermalVerticalPlate,
    CircularTubeGeometry,
    DittusBoelterSmoothCircularTube,
    FullyDevelopedLaminarCircularTube,
    HeatTransferCoefficient,
    HeatTransferCorrelation,
    HeatTransferCorrelationEvidence,
    HeatTransferValidityInterval,
    LaminarCircularTubeConservativeLowerBound,
    NaturalConvectionHeatTransferCoefficient,
    NaturalConvectionValidityInterval,
)
from golem.kernel.sheaf.interpreter import (
    BalanceInterpreter,
    Lowering,
    LoweredProblem,
    LoweringRejected,
    interpret_balance,
)
from golem.kernel.sheaf.interrogate import interrogate_balance_failure
from golem.kernel.sheaf.nusselt import (
    evaluate_heat_transfer_correlation,
    evaluate_natural_convection_correlation,
)
from golem.kernel.sheaf.problem import (
    AmbientExchange,
    BalanceProblem,
    CellAdjacency,
    CellSource,
    CellularComplex,
    DirectedTransport,
    FixedBoundary,
    SealedSolverConfig,
    SymmetricConductance,
)
from golem.kernel.sheaf.result import (
    Accepted,
    BalanceBridgeWitness,
    BalanceBudgetWitness,
    BalanceConditionCellWitness,
    BalanceConditioningWitness,
    BalanceDemandWitness,
    BalanceImbalanceObstruction,
    BalanceInterrogation,
    BalanceMatrixObstruction,
    BalanceResidualCellWitness,
    BalanceResidualObstruction,
    BalanceTopologyWitness,
    ConflictingFixedBalanceBoundaryObstruction,
    DegenerateBalanceInterfaceObstruction,
    DuplicateBalanceTermIdObstruction,
    EmptyBalanceDomainObstruction,
    InvalidBalanceCellObstruction,
    InvalidBalanceCoefficientObstruction,
    InvalidBalanceSolverConfigObstruction,
    InvalidBalanceTermIdObstruction,
    InvalidThermalParameterObstruction,
    NonConvergentBalanceObstruction,
    NonFiniteBalanceValueObstruction,
    Obstruction,
    Rejected,
    Result,
    UnanchoredBalanceComponentObstruction,
    UnsupportedHeatTransferRegimeObstruction,
    render_obstruction,
)
from golem.kernel.sheaf.section import (
    AmbientExchangeFlux,
    BalanceCell,
    BalanceInterfaceFlux,
    BalanceSolution,
    DirectedTransportFlux,
    FixedBoundarySupply,
    Section,
    SectionValue,
    SymmetricConductanceFlux,
)
from golem.kernel.sheaf.solve import solve_balance
from golem.kernel.sheaf.thermal import (
    AmbientHeatExchange,
    CoolantAdvectionLink,
    FixedTemperature,
    SolidConductionLink,
    ThermalBalanceProblem,
    ThermalEnergyReceipt,
    ThermalInterpreter,
    ThermalSolution,
    ThermalSource,
    WallHeatExchange,
    WallHeatFlux,
    solve_thermal_balance,
)
from golem.kernel.sheaf.vocabulary import (
    AmbientExchangeId,
    BalanceInterfaceId,
    BalanceMatrixFailure,
    BalanceProblemId,
    BalanceSolverParameter,
    BalanceSourceId,
    BalanceTermKind,
    BoundaryId,
    CellId,
    HeatTransferCorrelationId,
    HeatTransferCorrelationKind,
    HeatTransferValidityAxis,
    LaminarThermalBoundaryCondition,
    NaturalConvectionSurfaceOrientation,
    ThermalParameter,
    TurbulentThermalDirection,
)

__all__ = [
    "AmbientExchange",
    "AmbientExchangeFlux",
    "AmbientExchangeId",
    "AmbientHeatExchange",
    "Accepted",
    "BalanceCell",
    "BalanceBridgeWitness",
    "BalanceBudgetWitness",
    "BalanceConditionCellWitness",
    "BalanceConditioningWitness",
    "BalanceDemandWitness",
    "BalanceImbalanceObstruction",
    "BalanceInterfaceFlux",
    "BalanceInterfaceId",
    "BalanceInterpreter",
    "BalanceInterrogation",
    "BalanceMatrixFailure",
    "BalanceMatrixObstruction",
    "BalanceProblem",
    "BalanceProblemId",
    "BalanceResidualObstruction",
    "BalanceResidualCellWitness",
    "BalanceSolution",
    "BalanceSolverParameter",
    "BalanceSourceId",
    "BalanceTermKind",
    "BalanceTopologyWitness",
    "BoundaryId",
    "CellAdjacency",
    "CellId",
    "CellSource",
    "CellularComplex",
    "ChurchillChuIsothermalVerticalPlate",
    "CircularTubeGeometry",
    "ConflictingFixedBalanceBoundaryObstruction",
    "CoolantAdvectionLink",
    "DegenerateBalanceInterfaceObstruction",
    "DirectedTransport",
    "DirectedTransportFlux",
    "DittusBoelterSmoothCircularTube",
    "DuplicateBalanceTermIdObstruction",
    "EmptyBalanceDomainObstruction",
    "FixedBoundary",
    "FixedBoundarySupply",
    "FixedTemperature",
    "FullyDevelopedLaminarCircularTube",
    "HeatTransferCoefficient",
    "HeatTransferCorrelation",
    "HeatTransferCorrelationEvidence",
    "HeatTransferCorrelationId",
    "HeatTransferCorrelationKind",
    "HeatTransferValidityAxis",
    "HeatTransferValidityInterval",
    "InvalidBalanceCellObstruction",
    "InvalidBalanceCoefficientObstruction",
    "InvalidBalanceSolverConfigObstruction",
    "InvalidBalanceTermIdObstruction",
    "InvalidThermalParameterObstruction",
    "LaminarCircularTubeConservativeLowerBound",
    "LaminarThermalBoundaryCondition",
    "LoweredProblem",
    "Lowering",
    "LoweringRejected",
    "NaturalConvectionHeatTransferCoefficient",
    "NaturalConvectionSurfaceOrientation",
    "NaturalConvectionValidityInterval",
    "NonConvergentBalanceObstruction",
    "NonFiniteBalanceValueObstruction",
    "Obstruction",
    "Rejected",
    "Result",
    "SealedSolverConfig",
    "Section",
    "SectionValue",
    "SolidConductionLink",
    "SymmetricConductance",
    "SymmetricConductanceFlux",
    "ThermalBalanceProblem",
    "ThermalEnergyReceipt",
    "ThermalInterpreter",
    "ThermalParameter",
    "ThermalSolution",
    "ThermalSource",
    "TurbulentThermalDirection",
    "UnanchoredBalanceComponentObstruction",
    "UnsupportedHeatTransferRegimeObstruction",
    "WallHeatExchange",
    "WallHeatFlux",
    "evaluate_heat_transfer_correlation",
    "evaluate_natural_convection_correlation",
    "interpret_balance",
    "interrogate_balance_failure",
    "render_obstruction",
    "solve_balance",
    "solve_thermal_balance",
]
